// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1

TEST_CASE("Ex1 ", "[example]")
{
	struct Node *head, *tmp;
	int length;

	head = makeNumbers(10);
	struct Node *ptr = head;

	length = getLength(head);
	cout << "The length of the list " << length << endl;
	REQUIRE(length == 10);
	printNumbers(head);
	head = sortNumbers(head);
	printNumbers(head);
	tmp = head;
	for (int i = 0; i < length - 1; i++)
	{
		REQUIRE(tmp->value <= tmp->next->value);
		tmp = tmp->next;
	}
	cout << "--------------------------------------------------\n";
	cout << "--------------------------------------------------\n";
}